apiVersion: v1
kind: Service
metadata:
  name: accountingcollege-deployment
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: {{ .Values.nodePort.replicas  }}
    port: {{ .Values.port.replicas  }}
    protocol: TCP
    targetPort: {{ .Values.targetPort.replicas  }}
  selector:
    app: accountingcollege
  sessionAffinity: None
  type: LoadBalancer